version: "2"
services:
  server:
    build: ./server
    privileged: true
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    devices:
      - "/dev/sda1"
  frontend:
    build: ./frontend
    depends_on:
      - server
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
