version: "2"
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  server:
    build: ./server
    privileged: true
    expose:
      - "5000"
    ports:
      - "5000:5000"
    # env_file:
    #   - ./server/.env
    devices:
      - "/dev/sda1:/temp/"
  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - server
    ports:
      - "3000:3000"
    # env_file:
    #   - ./branch/.env
